#!/bin/bash

VERSION=1.0.0

cookies=/tmp/zm-cookies.txt
while [[ $# -gt 1 ]]; do
    key="$1"

    case $key in
        -H|--host)
        host="$2"
        shift
        ;;
        -u|--user)
        user="$2"
        shift
        ;;
        -p|--pass)
        pass="$2"
        shift
        ;;
        -h|--help)
        usage
        exit;
        ;;
        *)
        ;;
    esac
    shift
done

function usage() {
    echo "check_zm $VERSION"
    echo ""
    echo "Usage: check_zm -H http://zmhost.com/zm/ -u admin -p admin"
}

if [ "$host" == "" ] || [ "$user" == "" ] || [ "$pass" == "" ]; then
    usage
    exit;
fi

host=`echo $host | sed 's/\/*$//g'`

function jsonValue() {
    KEY=$1
    num=$2
    awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

function deleteCookies() {
    if [ -f "${cookies}" ]; then
        rm ${cookies}
    fi
}

function getStatus() {
    result=`curl --silent -b ${cookies} ${host}/api/host/daemonCheck.json`
    code=0

    if [[ $result == *": 0"* ]]; then
        code=1
    fi

    if [[ $result == *": 1"* ]]; then
        code=0
    fi
    return $code;
}

function printNagios () {
    code=$1
    if [ "$code" == "2" ]; then
        echo "CRITICAL - Plugin is not configured";
    fi

    if [ "$code" == "1" ]; then
        echo "Warning - ZM is stopped (version ${version})";
    fi

    if [ "$code" == "0" ]; then
        echo "OK - ZM is running (version ${version})";
    fi
}

function getVersion () {
    result=`curl --silent -b ${cookies} ${host}/api/host/getVersion.json`
    version=`echo $result | jsonValue version 1`
    version="$(echo -e "${version}" | sed -e 's/^[[:space:]]*//')"
    echo $version;
}

function restartZM () {
    result=`curl --silent -b ${cookies} ${host}/api/states/change/restart.json`
    echo $result;
}

deleteCookies;

function getCookies() {
    curl -s -o /dev/null -d "username=${user}&password=${pass}&action=login&view=console" -c ${cookies} ${host}/index.php
}

getCookies

wait

version=$(getVersion);
if [ "$version" == "" ]; then
    code=2
fi

if [ ! "$code" ]; then
    getStatus;
    code=$?;

    if [ "$code" == "2" ]; then
        # It's not running, restart..
        restartZM;
    fi
fi

printNagios $code;

deleteCookies;

exit $code
